# Change this and move to .config.yml
# where it will not be checked in
:gitconfig:
  :location: ".gitconfig"
  :name: "Ben Radler"
  :email: ""
  :github_user: ""
  :github_token: ""
:gemrc:
  :location: ".gemrc"
  :sources: []
:gem_credentials:
  :location: ".gem/credentials"
  :api_key: ""
:irssi_config:
  :location: ".irssi/config"
  :irc_nick: ""
  :irc_nick_password: ""