---
# Change this and move to .config.yml
# where it will not be checked in
:gitconfig:
  :location: ".gitconfig"
  :name: "ChangeMe"
  :email: "ChangeMe"
  :github_user: "ChangeMe"
  :github_token: "GithubToken"
:gemrc:
  :location: ".gemrc"
  :sources: []
:gem_credentials:
  :location: ".gem/credentials"
  :api_key: "gemcutter token"
:irssi_config:
  :location: ".irssi/config"
  :irc_nick: "mynick"
  :irc_nick_password: "mypass"
