complete -c rbenv -l commands --description 'List all available rbenv commands'
complete -c rbenv -l local --description 'Set or show the local application-specific Ruby version'
complete -c rbenv -l global --description 'Set or show the global Ruby version'
complete -c rbenv -l shell --description 'Set or show the shell-specific Ruby version'
complete -c rbenv -l install --description 'Install a Ruby version using the ruby-build plugin'
complete -c rbenv -l uninstall --description 'Uninstall a specific Ruby version'
complete -c rbenv -l rehash --description 'Rehash rbenv shims (run this after installing executables)'
complete -c rbenv -l version --description 'Show the current Ruby version and its origin'
complete -c rbenv -l versions --description 'List all Ruby versions available to rbenv'
complete -c rbenv -l which --description 'Display the full path to an executable'
complete -c rbenv -l whence --description 'List all Ruby versions that contain the given executable'
